print("Evaluación Examen Transversal Programación y Redes Virtualizadas")
print("\nIntegrantes del grupo:")
print("- Benjamin Gutierrez")
print("- Samuel Toloza")
print("- Benjamin Lizana")
print("- Cristopher Araya")